site_name: "Tactical RMM"
nav:
  - Home: index.md
site_description: "A remote monitoring and management tool for Windows computers"
site_author: "wh1te909"

# Repository
repo_name: "wh1te909/tacticalrmm"
repo_url: "https://github.com/wh1te909/tacticalrmm"
edit_uri: ""

theme:
  name: "material"
  custom_dir: "theme"
  logo: "images/onit.ico"
  favicon: "images/favicon.ico"
  language: "en"
  palette:
    primary: "white"
    accent: "indigo"
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/wh1te909/tacticalrmm"
markdown_extensions:
  - pymdownx.inlinehilite
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
