name: Deploy Docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip
      - run: pip install --upgrade setuptools wheel
      - run: pip install mkdocs mkdocs-material==8.5.11 pymdown-extensions
      - run: mkdocs gh-deploy --force
